/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\homestead2.glb -T -j -t 
Files: .\homestead2.glb [16.01MB] > E:\Code\glb-preview\public\homestead2-transformed.glb [858.73KB] (95%)
*/

import * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import { a, useSpring } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    tree: THREE.Mesh;
    green: THREE.Mesh;
    Bonfire: THREE.Mesh;
    Hen: THREE.Mesh;
    Shovel4: THREE.Mesh;
    Trolley: THREE.Mesh;
    Water_Shower: THREE.Mesh;
    Well: THREE.Mesh;
    Farm_House: THREE.Mesh;
    Ground001: THREE.Mesh;
    House_Part: THREE.Mesh;
    Plant_Sand: THREE.Mesh;
    Road: THREE.Mesh;
    Horse: THREE.Mesh;
    House: THREE.Mesh;
    Big_Fan: THREE.Mesh;
    Grass: THREE.Mesh;
    Plants: THREE.Mesh;
    Hen_House: THREE.Mesh;
    Lamp: THREE.Mesh;
    Part: THREE.Mesh;
    Pitch_Fork: THREE.Mesh;
    Tent: THREE.Mesh;
    Cut_Tree: THREE.Mesh;
    Fence: THREE.Mesh;
    Out_Door: THREE.Mesh;
    Pant_Shirt_Hang: THREE.Mesh;
    Sand_Stone: THREE.Mesh;
    Tree: THREE.Mesh;
    Tree6: THREE.Mesh;
    Washroom: THREE.Mesh;
    Water_Basket: THREE.Mesh;
    Wood: THREE.Mesh;
  };
  materials: {
    Tree_Fence_Sand_Material: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Bonfire_Well_Material: THREE.MeshStandardMaterial;
    Farm_House_Material: THREE.MeshStandardMaterial;
    Ground_Material: THREE.MeshStandardMaterial;
    Horse_Material: THREE.MeshStandardMaterial;
    House_Material: THREE.MeshStandardMaterial;
    Plants_Grass_Fan_Material: THREE.MeshStandardMaterial;
    Tent_Hen_House_Material: THREE.MeshStandardMaterial;
  };
  animations: any[];
};

function PopInGroup({ stage, currentStage, children }: any) {
  const { scale } = useSpring({
    scale: currentStage >= stage ? 1 : 0,
    config: { tension: 170, friction: 15 },
  });
  return <a.group scale={scale as any}>{children}</a.group>;
}

function DropDownGroup({ stage, currentStage, children }: any) {
  const { scale, position } = useSpring({
    scale: currentStage >= stage ? 1 : 0,
    position: currentStage >= stage ? [0, 0, 0] : [0, 0, 5000],
    config: { tension: 120, friction: 14 },
  });
  return (
    <a.group scale={scale as any} position={position as any}>
      {children}
    </a.group>
  );
}

export function Model({ currentStage = 1, ...props }: any) {
  const { nodes, materials } = useGLTF(
    "/homestead2-transformed.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        {/* Stage 1: Base Land & Trees */}
        <group>
          <mesh
            receiveShadow
            geometry={nodes.Ground001.geometry}
            material={materials.Ground_Material}
          />
          <mesh
            castShadow
            geometry={nodes.green.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Road.geometry}
            material={materials.Ground_Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sand_Stone.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree6.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </group>

        {/* Stage 2: Grass Detail Appears */}
        <PopInGroup stage={2} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grass.geometry}
            material={materials.Plants_Grass_Fan_Material}
          />
        </PopInGroup>

        {/* Stage 3: Settlers Arrive (Tents) */}
        <DropDownGroup stage={3} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tent.geometry}
            material={materials.Tent_Hen_House_Material}
          />
        </DropDownGroup>

        {/* Stage 4: First Fire */}
        <PopInGroup stage={4} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bonfire.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </PopInGroup>

        {/* Stage 5: Basic Sanitation */}
        <DropDownGroup stage={5} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Washroom.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </DropDownGroup>

        {/* Stage 6: Groundbreaking Tools */}
        <PopInGroup stage={6} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shovel4.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </PopInGroup>

        {/* Stage 7: Clearing Land */}
        <DropDownGroup stage={7} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cut_Tree.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </DropDownGroup>

        {/* Stage 8: Securing Water */}
        <DropDownGroup stage={8} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Well.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </DropDownGroup>

        {/* Stage 9: Tilling the Soil */}
        <DropDownGroup stage={9} currentStage={currentStage}>
          <mesh
            receiveShadow
            geometry={nodes.Plant_Sand.geometry}
            material={materials.Ground_Material}
          />
        </DropDownGroup>

        {/* Stage 10: Watering Equipment */}
        <PopInGroup stage={10} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Water_Shower.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </PopInGroup>

        {/* Stage 11: Chopped Fuel/Materials */}
        <PopInGroup stage={11} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </PopInGroup>

        {/* Stage 12: Building the Coop */}
        <DropDownGroup stage={12} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hen_House.geometry}
            material={materials.Tent_Hen_House_Material}
          />
        </DropDownGroup>

        {/* Stage 13: Evening Light */}
        <PopInGroup stage={13} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp.geometry}
            material={materials.Tent_Hen_House_Material}
          />
        </PopInGroup>

        {/* Stage 14: Crops Sprout */}
        <PopInGroup stage={14} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plants.geometry}
            material={materials.Plants_Grass_Fan_Material}
          />
        </PopInGroup>

        {/* Stage 15: Perimeter Fencing */}
        <DropDownGroup stage={15} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fence.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </DropDownGroup>

        {/* Stage 16: Well Bucket */}
        <PopInGroup stage={16} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Water_Basket.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </PopInGroup>

        {/* Stage 17: Chickens Arrive */}
        <PopInGroup stage={17} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hen.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </PopInGroup>

        {/* Stage 18: Wheelbarrows */}
        <PopInGroup stage={18} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Trolley.geometry}
            material={materials.Bonfire_Well_Material}
          />
        </PopInGroup>

        {/* Stage 19: Windmill */}
        <PopInGroup stage={19} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Big_Fan.geometry}
            material={materials.Plants_Grass_Fan_Material}
          />
        </PopInGroup>

        {/* Stage 20: Hay Storage */}
        <DropDownGroup stage={20} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part.geometry}
            material={materials.Tent_Hen_House_Material}
          />
        </DropDownGroup>

        {/* Stage 21: Horse & Wagon */}
        <PopInGroup stage={21} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Horse.geometry}
            material={materials.Horse_Material}
          />
        </PopInGroup>

        {/* Stage 22: Completed Residence */}
        <DropDownGroup stage={22} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.House_Part.geometry}
            material={materials.Ground_Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.House.geometry}
            material={materials.House_Material}
          />
        </DropDownGroup>

        {/* Stage 23: Storm Shelter */}
        <DropDownGroup stage={23} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Out_Door.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </DropDownGroup>

        {/* Stage 24: Domestic Details (Clothesline) */}
        <PopInGroup stage={24} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pant_Shirt_Hang.geometry}
            material={materials.Tree_Fence_Sand_Material}
          />
        </PopInGroup>

        {/* Stage 25: Big Red Barn */}
        <DropDownGroup stage={25} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Farm_House.geometry}
            material={materials.Farm_House_Material}
          />
        </DropDownGroup>

        {/* Stage 26: Pitchforks (Leaning on the Barn) */}
        <PopInGroup stage={26} currentStage={currentStage}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pitch_Fork.geometry}
            material={materials.Tent_Hen_House_Material}
          />
        </PopInGroup>
      </group>
    </group>
  );
}

useGLTF.preload("/homestead2-transformed.glb");