/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/homestead_main.glb -t -o src/components/HomesteadMain.tsx 
*/

import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    Bonfire: THREE.Mesh
    Hen: THREE.Mesh
    Shovel4: THREE.Mesh
    Trolley: THREE.Mesh
    Water_Shower: THREE.Mesh
    Well: THREE.Mesh
    Ground001: THREE.Mesh
    House_Part: THREE.Mesh
    Plant_Sand: THREE.Mesh
    Road: THREE.Mesh
    Big_Fan: THREE.Mesh
    Grass: THREE.Mesh
    Plants: THREE.Mesh
    Hen_House: THREE.Mesh
    Lamp: THREE.Mesh
    Part: THREE.Mesh
    Pitch_Fork: THREE.Mesh
    Tent: THREE.Mesh
    Cut_Tree: THREE.Mesh
    Fence: THREE.Mesh
    Out_Door: THREE.Mesh
    Pant_Shirt_Hang: THREE.Mesh
    Sand_Stone: THREE.Mesh
    Tree: THREE.Mesh
    Tree6: THREE.Mesh
    Washroom: THREE.Mesh
    Water_Basket: THREE.Mesh
    Wood: THREE.Mesh
    Farm_House: THREE.Mesh
    Horse: THREE.Mesh
    House: THREE.Mesh
  }
  materials: {
    Bonfire_Well_Material: THREE.MeshStandardMaterial
    Ground_Material: THREE.MeshStandardMaterial
    Plants_Grass_Fan_Material: THREE.MeshStandardMaterial
    Tent_Hen_House_Material: THREE.MeshStandardMaterial
    Tree_Fence_Sand_Material: THREE.MeshStandardMaterial
    Farm_House_Material: THREE.MeshStandardMaterial
    Horse_Material: THREE.MeshStandardMaterial
    House_Material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

function PopInGroup({ stage, currentStage, children }: { stage: number, currentStage: number, children: React.ReactNode }) {
  const { scale } = useSpring({
    scale: currentStage >= stage ? 1 : 0,
    config: { mass: 2, tension: 150, friction: 18 } // Slower, heavier pop-in
  });
  return <a.group scale={scale}>{children}</a.group>;
}

function DropDownGroup({ stage, currentStage, children }: { stage: number, currentStage: number, children: React.ReactNode }) {
  const { z, scale } = useSpring({
    z: currentStage >= stage ? 0 : -5000,
    scale: currentStage >= stage ? 1 : 0,
    config: (key) => 
      key === 'scale' 
        ? { tension: 300, friction: 14 } 
        : { mass: 2, tension: 100, friction: 20 }
  });
  
  // Use position={[0, 0, z]} via interpolation to guarantee it applies correctly
  return (
    <a.group 
      position={z.to((zVal) => [0, 0, zVal])} 
      scale={scale}
    >
      {children}
    </a.group>
  );
}

export function Model({ currentStage = 1, ...props }: any) {
  const { nodes, materials } = useGLTF('/homestead_main.glb') as unknown as GLTFResult

  

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        
        {/* Stage 1: Base ground always visible */}
        <group>
          <mesh geometry={nodes.Grass.geometry} material={materials.Plants_Grass_Fan_Material} />
          <mesh geometry={nodes.Ground001.geometry} material={materials.Ground_Material} />
        </group>

        {/* Stage 2 */}
        <PopInGroup currentStage={currentStage} stage={2}>
          <mesh geometry={nodes.Plant_Sand.geometry} material={materials.Ground_Material} />
          <mesh geometry={nodes.Sand_Stone.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 3 */}
        <DropDownGroup currentStage={currentStage} stage={3}>
          <mesh geometry={nodes.Road.geometry} material={materials.Ground_Material} />
        </DropDownGroup>

        {/* Stage 4 */}
        <PopInGroup currentStage={currentStage} stage={4}>
          <mesh geometry={nodes.Cut_Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
          <mesh geometry={nodes.Wood.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 5 */}
        <DropDownGroup currentStage={currentStage} stage={5}>
          <mesh geometry={nodes.Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 6 */}
        <DropDownGroup currentStage={currentStage} stage={6}>
          <mesh geometry={nodes.Tree6.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 7 */}
        <PopInGroup currentStage={currentStage} stage={7}>
          <mesh geometry={nodes.Big_Fan.geometry} material={materials.Plants_Grass_Fan_Material} />
        </PopInGroup>

        {/* Stage 8 */}
        <PopInGroup currentStage={currentStage} stage={8}>
          <mesh geometry={nodes.Plants.geometry} material={materials.Plants_Grass_Fan_Material} />
        </PopInGroup>

        {/* Stage 9 */}
        <DropDownGroup currentStage={currentStage} stage={9}>
          <mesh geometry={nodes.Well.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 10 */}
        <PopInGroup currentStage={currentStage} stage={10}>
          <mesh geometry={nodes.Water_Basket.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 11 */}
        <DropDownGroup currentStage={currentStage} stage={11}>
          <mesh geometry={nodes.Water_Shower.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 12 */}
        <DropDownGroup currentStage={currentStage} stage={12}>
          <mesh geometry={nodes.Washroom.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 13 */}
        <DropDownGroup currentStage={currentStage} stage={13}>
          <mesh geometry={nodes.Tent.geometry} material={materials.Tent_Hen_House_Material} />
        </DropDownGroup>

        {/* Stage 14 */}
        <PopInGroup currentStage={currentStage} stage={14}>
          <mesh geometry={nodes.Bonfire.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 15 */}
        <PopInGroup currentStage={currentStage} stage={15}>
          <mesh geometry={nodes.Lamp.geometry} material={materials.Tent_Hen_House_Material} />
        </PopInGroup>

        {/* Stage 16 */}
        <PopInGroup currentStage={currentStage} stage={16}>
          <mesh geometry={nodes.Shovel4.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 17 */}
        <PopInGroup currentStage={currentStage} stage={17}>
          <mesh geometry={nodes.Pitch_Fork.geometry} material={materials.Tent_Hen_House_Material} />
        </PopInGroup>

        {/* Stage 18 */}
        <PopInGroup currentStage={currentStage} stage={18}>
          <mesh geometry={nodes.Trolley.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 19 */}
        <DropDownGroup currentStage={currentStage} stage={19}>
          <mesh geometry={nodes.Fence.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 20 */}
        <DropDownGroup currentStage={currentStage} stage={20}>
          <mesh geometry={nodes.Hen_House.geometry} material={materials.Tent_Hen_House_Material} />
          <mesh geometry={nodes.Hen.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 21 */}
        <PopInGroup currentStage={currentStage} stage={21}>
          <mesh geometry={nodes.Horse.geometry} material={materials.Horse_Material} />
        </PopInGroup>

        {/* Stage 22 */}
        <DropDownGroup currentStage={currentStage} stage={22}>
          <mesh geometry={nodes.House_Part.geometry} material={materials.Ground_Material} />
        </DropDownGroup>

        {/* Stage 23 */}
        <DropDownGroup currentStage={currentStage} stage={23}>
          <mesh geometry={nodes.Part.geometry} material={materials.Tent_Hen_House_Material} />
        </DropDownGroup>

        {/* Stage 24 */}
        <DropDownGroup currentStage={currentStage} stage={24}>
          <mesh geometry={nodes.House.geometry} material={materials.House_Material} />
          <mesh geometry={nodes.Out_Door.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 25 */}
        <PopInGroup currentStage={currentStage} stage={25}>
          <mesh geometry={nodes.Pant_Shirt_Hang.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 26 */}
        <DropDownGroup currentStage={currentStage} stage={26}>
          <mesh geometry={nodes.Farm_House.geometry} material={materials.Farm_House_Material} />
        </DropDownGroup>

      </group>
    </group>
  )
}

useGLTF.preload('/homestead_main.glb')

