/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/homestead_main.glb -t -o src/components/HomesteadMain.tsx 
*/

import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

import { useGLTF } from '@react-three/drei'


type GLTFResult = GLTF & {
  nodes: {
    Bonfire: THREE.Mesh
    Hen: THREE.Mesh
    Shovel4: THREE.Mesh
    Trolley: THREE.Mesh
    Water_Shower: THREE.Mesh
    Well: THREE.Mesh
    Ground001: THREE.Mesh
    House_Part: THREE.Mesh
    Plant_Sand: THREE.Mesh
    Road: THREE.Mesh
    Big_Fan: THREE.Mesh
    Grass: THREE.Mesh
    Plants: THREE.Mesh
    Hen_House: THREE.Mesh
    Lamp: THREE.Mesh
    Part: THREE.Mesh
    Pitch_Fork: THREE.Mesh
    Tent: THREE.Mesh
    Cut_Tree: THREE.Mesh
    Fence: THREE.Mesh
    Out_Door: THREE.Mesh
    Pant_Shirt_Hang: THREE.Mesh
    Sand_Stone: THREE.Mesh
    Tree: THREE.Mesh
    Tree6: THREE.Mesh
    Washroom: THREE.Mesh
    Water_Basket: THREE.Mesh
    Wood: THREE.Mesh
    Farm_House: THREE.Mesh
    Horse: THREE.Mesh
    House: THREE.Mesh
  }
  materials: {
    Bonfire_Well_Material: THREE.MeshStandardMaterial
    Ground_Material: THREE.MeshStandardMaterial
    Plants_Grass_Fan_Material: THREE.MeshStandardMaterial
    Tent_Hen_House_Material: THREE.MeshStandardMaterial
    Tree_Fence_Sand_Material: THREE.MeshStandardMaterial
    Farm_House_Material: THREE.MeshStandardMaterial
    Horse_Material: THREE.MeshStandardMaterial
    House_Material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/homestead_main.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Farm_House.geometry} material={materials.Farm_House_Material} />
        <mesh geometry={nodes.Horse.geometry} material={materials.Horse_Material} />
        <mesh geometry={nodes.House.geometry} material={materials.House_Material} />
        <mesh geometry={nodes.Bonfire.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Hen.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Shovel4.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Trolley.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Water_Shower.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Well.geometry} material={materials.Bonfire_Well_Material} />
        <mesh geometry={nodes.Ground001.geometry} material={materials.Ground_Material} />
        <mesh geometry={nodes.House_Part.geometry} material={materials.Ground_Material} />
        <mesh geometry={nodes.Plant_Sand.geometry} material={materials.Ground_Material} />
        <mesh geometry={nodes.Road.geometry} material={materials.Ground_Material} />
        <mesh geometry={nodes.Big_Fan.geometry} material={materials.Plants_Grass_Fan_Material} />
        <mesh geometry={nodes.Grass.geometry} material={materials.Plants_Grass_Fan_Material} />
        <mesh geometry={nodes.Plants.geometry} material={materials.Plants_Grass_Fan_Material} />
        <mesh geometry={nodes.Hen_House.geometry} material={materials.Tent_Hen_House_Material} />
        <mesh geometry={nodes.Lamp.geometry} material={materials.Tent_Hen_House_Material} />
        <mesh geometry={nodes.Part.geometry} material={materials.Tent_Hen_House_Material} />
        <mesh geometry={nodes.Pitch_Fork.geometry} material={materials.Tent_Hen_House_Material} />
        <mesh geometry={nodes.Tent.geometry} material={materials.Tent_Hen_House_Material} />
        <mesh geometry={nodes.Cut_Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Fence.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Out_Door.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Pant_Shirt_Hang.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Sand_Stone.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Tree6.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Washroom.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Water_Basket.geometry} material={materials.Tree_Fence_Sand_Material} />
        <mesh geometry={nodes.Wood.geometry} material={materials.Tree_Fence_Sand_Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/homestead_main.glb')
