/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\homestead2.glb -T -j -t 
Files: .\homestead2.glb [16.01MB] > E:\Code\glb-preview\public\homestead2-transformed.glb [858.73KB] (95%)
*/

import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    tree: THREE.Mesh
    green: THREE.Mesh
    Bonfire: THREE.Mesh
    Hen: THREE.Mesh
    Shovel4: THREE.Mesh
    Trolley: THREE.Mesh
    Water_Shower: THREE.Mesh
    Well: THREE.Mesh
    Farm_House: THREE.Mesh
    Ground001: THREE.Mesh
    House_Part: THREE.Mesh
    Plant_Sand: THREE.Mesh
    Road: THREE.Mesh
    Horse: THREE.Mesh
    House: THREE.Mesh
    Big_Fan: THREE.Mesh
    Grass: THREE.Mesh
    Plants: THREE.Mesh
    Hen_House: THREE.Mesh
    Lamp: THREE.Mesh
    Part: THREE.Mesh
    Pitch_Fork: THREE.Mesh
    Tent: THREE.Mesh
    Cut_Tree: THREE.Mesh
    Fence: THREE.Mesh
    Out_Door: THREE.Mesh
    Pant_Shirt_Hang: THREE.Mesh
    Sand_Stone: THREE.Mesh
    Tree: THREE.Mesh
    Tree6: THREE.Mesh
    Washroom: THREE.Mesh
    Water_Basket: THREE.Mesh
    Wood: THREE.Mesh
  }
  materials: {
    Tree_Fence_Sand_Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Bonfire_Well_Material: THREE.MeshStandardMaterial
    Farm_House_Material: THREE.MeshStandardMaterial
    Ground_Material: THREE.MeshStandardMaterial
    Horse_Material: THREE.MeshStandardMaterial
    House_Material: THREE.MeshStandardMaterial
    Plants_Grass_Fan_Material: THREE.MeshStandardMaterial
    Tent_Hen_House_Material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

function PopInGroup({ stage, currentStage, children }: any) {
  const { scale } = useSpring({
    scale: currentStage >= stage ? 1 : 0,
    config: { tension: 170, friction: 15 }
  })
  return <a.group scale={scale as any}>{children}</a.group>
}

function DropDownGroup({ stage, currentStage, children }: any) {
  const { scale, position } = useSpring({
    scale: currentStage >= stage ? 1 : 0,
    position: currentStage >= stage ? [0, 0, 0] : [0, 0, 5000],
    config: { tension: 120, friction: 14 }
  })
  return <a.group scale={scale as any} position={position as any}>{children}</a.group>
}

export function Model({ currentStage = 1, ...props }: any) {
  const { nodes, materials } = useGLTF('/homestead2-transformed.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        
        {/* Stage 1: Base ground always visible */}
        <group>
          <mesh geometry={nodes.Grass.geometry} material={materials.Plants_Grass_Fan_Material} />
          <mesh geometry={nodes.Ground001.geometry} material={materials.Ground_Material} />
          <mesh geometry={nodes.green.geometry} material={materials['Material.001']} />
        </group>

        {/* Stage 2 */}
        <PopInGroup stage={2} currentStage={currentStage}>
          <mesh geometry={nodes.Plant_Sand.geometry} material={materials.Ground_Material} />
          <mesh geometry={nodes.Sand_Stone.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 3 */}
        <DropDownGroup stage={3} currentStage={currentStage}>
          <mesh geometry={nodes.Road.geometry} material={materials.Ground_Material} />
        </DropDownGroup>

        {/* Stage 4 */}
        <PopInGroup stage={4} currentStage={currentStage}>
          <mesh geometry={nodes.Cut_Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
          <mesh geometry={nodes.Wood.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 5 */}
        <DropDownGroup stage={5} currentStage={currentStage}>
          <mesh geometry={nodes.Tree.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 6 */}
        <DropDownGroup stage={6} currentStage={currentStage}>
          <mesh geometry={nodes.Tree6.geometry} material={materials.Tree_Fence_Sand_Material} />
          <mesh geometry={nodes.tree.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 7 */}
        <PopInGroup stage={7} currentStage={currentStage}>
          <mesh geometry={nodes.Big_Fan.geometry} material={materials.Plants_Grass_Fan_Material} />
        </PopInGroup>

        {/* Stage 8 */}
        <PopInGroup stage={8} currentStage={currentStage}>
          <mesh geometry={nodes.Plants.geometry} material={materials.Plants_Grass_Fan_Material} />
        </PopInGroup>

        {/* Stage 9 */}
        <DropDownGroup stage={9} currentStage={currentStage}>
          <mesh geometry={nodes.Well.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 10 */}
        <PopInGroup stage={10} currentStage={currentStage}>
          <mesh geometry={nodes.Water_Basket.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 11 */}
        <DropDownGroup stage={11} currentStage={currentStage}>
          <mesh geometry={nodes.Water_Shower.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 12 */}
        <DropDownGroup stage={12} currentStage={currentStage}>
          <mesh geometry={nodes.Washroom.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 13 */}
        <DropDownGroup stage={13} currentStage={currentStage}>
          <mesh geometry={nodes.Tent.geometry} material={materials.Tent_Hen_House_Material} />
        </DropDownGroup>

        {/* Stage 14 */}
        <PopInGroup stage={14} currentStage={currentStage}>
          <mesh geometry={nodes.Bonfire.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 15 */}
        <PopInGroup stage={15} currentStage={currentStage}>
          <mesh geometry={nodes.Lamp.geometry} material={materials.Tent_Hen_House_Material} />
        </PopInGroup>

        {/* Stage 16 */}
        <PopInGroup stage={16} currentStage={currentStage}>
          <mesh geometry={nodes.Shovel4.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 17 */}
        <PopInGroup stage={17} currentStage={currentStage}>
          <mesh geometry={nodes.Pitch_Fork.geometry} material={materials.Tent_Hen_House_Material} />
        </PopInGroup>

        {/* Stage 18 */}
        <PopInGroup stage={18} currentStage={currentStage}>
          <mesh geometry={nodes.Trolley.geometry} material={materials.Bonfire_Well_Material} />
        </PopInGroup>

        {/* Stage 19 */}
        <DropDownGroup stage={19} currentStage={currentStage}>
          <mesh geometry={nodes.Fence.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 20 */}
        <DropDownGroup stage={20} currentStage={currentStage}>
          <mesh geometry={nodes.Hen_House.geometry} material={materials.Tent_Hen_House_Material} />
          <mesh geometry={nodes.Hen.geometry} material={materials.Bonfire_Well_Material} />
        </DropDownGroup>

        {/* Stage 21 */}
        <PopInGroup stage={21} currentStage={currentStage}>
          <mesh geometry={nodes.Horse.geometry} material={materials.Horse_Material} />
        </PopInGroup>

        {/* Stage 22 */}
        <DropDownGroup stage={22} currentStage={currentStage}>
          <mesh geometry={nodes.House_Part.geometry} material={materials.Ground_Material} />
        </DropDownGroup>

        {/* Stage 23 */}
        <DropDownGroup stage={23} currentStage={currentStage}>
          <mesh geometry={nodes.Part.geometry} material={materials.Tent_Hen_House_Material} />
        </DropDownGroup>

        {/* Stage 24 */}
        <DropDownGroup stage={24} currentStage={currentStage}>
          <mesh geometry={nodes.House.geometry} material={materials.House_Material} />
          <mesh geometry={nodes.Out_Door.geometry} material={materials.Tree_Fence_Sand_Material} />
        </DropDownGroup>

        {/* Stage 25 */}
        <PopInGroup stage={25} currentStage={currentStage}>
          <mesh geometry={nodes.Pant_Shirt_Hang.geometry} material={materials.Tree_Fence_Sand_Material} />
        </PopInGroup>

        {/* Stage 26 */}
        <DropDownGroup stage={26} currentStage={currentStage}>
          <mesh geometry={nodes.Farm_House.geometry} material={materials.Farm_House_Material} />
        </DropDownGroup>

      </group>
    </group>
  )
}

useGLTF.preload('/homestead2-transformed.glb')
